name: "Package Version Action"
description: "GitHub Action to get the package.json version and a SHA suffix"
author: "Koj <https://github.com/koj.co>"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "umbrella"
  color: "purple"
